// <auto-generated />
using System;
using ContactPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactPersistence.Migrations
{
    [DbContext(typeof(ContactBookContext))]
    partial class ContactBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("ContactPersistence.Models.BusinessDepartment", b =>
                {
                    b.Property<int>("BusinessDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BusinessDepartmentId");

                    b.ToTable("BusinessDepartments");
                });

            modelBuilder.Entity("ContactPersistence.Models.BusinessPosition", b =>
                {
                    b.Property<int>("BusinessPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BusinessPositionId");

                    b.ToTable("BusinessPositions");
                });

            modelBuilder.Entity("ContactPersistence.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusinessPositionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Names")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudonymous")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.HasIndex("BusinessDepartmentId");

                    b.HasIndex("BusinessPositionID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ContactPersistence.Models.Contact", b =>
                {
                    b.HasOne("ContactPersistence.Models.BusinessDepartment", "BusinessDepartment")
                        .WithMany("Contacts")
                        .HasForeignKey("BusinessDepartmentId");

                    b.HasOne("ContactPersistence.Models.BusinessPosition", "BusinessPosition")
                        .WithMany("Contacts")
                        .HasForeignKey("BusinessPositionID");

                    b.Navigation("BusinessDepartment");

                    b.Navigation("BusinessPosition");
                });

            modelBuilder.Entity("ContactPersistence.Models.BusinessDepartment", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("ContactPersistence.Models.BusinessPosition", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
